import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { Alert, Card, CardHeader, PageHeader } from "@/components/ui";
import { prisma } from "@/lib/db";
import { bpToInput, centsToInput, toDateInput } from "@/lib/format";
import { getQuotation } from "@/lib/quotations";
import { NotFoundError } from "@/lib/errors";
import { requireTenant } from "@/lib/tenant";
import { updateQuotationAction } from "@/server/quotation-actions";
import { QuotationEditor } from "../../quotation-editor";

export const metadata: Metadata = { title: "Edit quotation" };

export default async function EditQuotationPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { session, profile } = await requireTenant();

  let quotation;
  try {
    quotation = await getQuotation(session.organizationId, id);
  } catch (error) {
    if (error instanceof NotFoundError) notFound();
    throw error;
  }

  // Editing a sent quotation would silently change what the customer received.
  if (quotation.status !== "draft") redirect(`/quotations/${id}`);

  const [customers, products] = await Promise.all([
    prisma.customer.findMany({
      where: { organizationId: session.organizationId },
      orderBy: { name: "asc" },
      select: { id: true, name: true, company: true },
    }),
    prisma.product.findMany({
      where: { organizationId: session.organizationId, active: true },
      orderBy: { name: "asc" },
      select: { id: true, name: true, description: true, unit: true, unitPriceCents: true, taxRateBp: true },
    }),
  ]);

  return (
    <>
      <PageHeader title={`Edit ${quotation.number}`} description={quotation.title} />

      {quotation.aiGenerated ? (
        <Alert tone="brand" title="This draft was written by AI">
          Generated by {quotation.aiModel ?? "the configured model"}. Check every line and price
          before you send it.
        </Alert>
      ) : null}

      <Card>
        <CardHeader title="Details" />
        <QuotationEditor
          action={updateQuotationAction}
          customers={customers}
          products={products}
          defaultCurrency={profile.currency}
          defaultTaxRateBp={profile.taxRateBp}
          locale={profile.locale}
          submitLabel="Save quotation"
          cancelHref={`/quotations/${quotation.id}`}
          values={{
            id: quotation.id,
            customerId: quotation.customerId,
            inquiryId: quotation.inquiryId ?? "",
            title: quotation.title,
            currency: quotation.currency,
            discount: centsToInput(quotation.discountCents),
            notes: quotation.notes ?? "",
            terms: quotation.terms ?? "",
            validUntil: toDateInput(quotation.validUntil),
            lines: quotation.items.map((item) => ({
              productId: item.productId ?? "",
              description: item.description,
              quantity: String(item.quantity),
              unit: item.unit,
              unitPrice: centsToInput(item.unitPriceCents),
              taxRate: bpToInput(item.taxRateBp),
            })),
          }}
        />
      </Card>
    </>
  );
}
